### ISSUE TITLE
Error when starting `localstack` with bootstrapped extension

### ISSUE THREAD

**Issue by thepalbi** [localstack/localstack-extensions#8]
Hi! I'm experimenting a bit with localstack extensions. My goal is, if I see a fit, develop an extension to mimic `CloudWatch` data. 

I followed the instruction for creating the extension boilerplate, that works just fine. However, when attempting to start `localstack` with the extension enabled, that is:
```
EXTENSION_DEV_MODE=1 localstack start
```
I'm getting the following errors:

```
[17:28:35] starting LocalStack in Docker mode 🐳                                                                                           localstack.py:138
Traceback (most recent call last):
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/bin/localstack", line 23, in <module>
    main()
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/bin/localstack", line 19, in main
    main.main()
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/localstack/cli/main.py", line 11, in main
    cli()
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/localstack/cli/localstack.py", line 140, in cmd_start
    bootstrap.prepare_host(console)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 77, in wrapped
    return f(*args, **kwargs)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 625, in prepare_host
    hooks.prepare_host.run()
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/localstack/runtime/hooks.py", line 63, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/plugin/core.py", line 183, in __call__
    return self.fn(*args, **kwargs)
  File "/Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator/.venv/lib/python3.10/site-packages/localstack_ext/extensions/plugins.py", line 14, in configure_extensions_dev_host
    def configure_extensions_dev_host():from localstack_ext.extensions.bootstrap import run_on_configure_host_hook as A;A()
ModuleNotFoundError: No module named 'localstack_ext.extensions.bootstrap'
```

Any ideas? Just in case it helps, here's a pip freeze:
```
(.venv) ➜  cloudwatch-metrics-emulator pip freeze
apispec==6.3.0
boto3==1.26.100
botocore==1.29.100
cachetools==5.0.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
# Editable install with no version control (cloudwatch-metrics-emulator==0.0.1)
-e /Users/pablo/work/experiments/local-stack-tests/cloudwatch-metrics-emulator
cryptography==40.0.1
dill==0.3.2
dnslib==0.9.23
dnspython==2.3.0
ecdsa==0.18.0
idna==3.4
jmespath==1.0.1
localstack==1.4.0
localstack-client==2.0
localstack-ext==1.4.0
markdown-it-py==2.2.0
mdurl==0.1.2
packaging==23.0
pbr==5.11.1
plux==1.3.1
psutil==5.9.4
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.21
Pygments==2.14.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-jose==3.3.0
PyYAML==6.0
requests==2.28.2
rich==13.3.3
rsa==4.9
s3transfer==0.6.0
semver==2.13.0
six==1.16.0
stevedore==5.0.0
tabulate==0.9.0
tailer==0.4.1
urllib3==1.26.15
```

**Comment by alexrashed** [comment]
Hi @thepalbi!
This is due to out upcoming changes with v2.0, where we will separate the community and the pro image.
For more information, please refer to https://github.com/localstack/localstack/issues/7882.
TSince you are not setting an API key, the CLI is `localstack/localstack` (i.e. the community image) when starting up.
However, the latest version of this image does not have our pro extensions in it anymore (as described in the linked release notification issue). Since extensions are a Pro feature, they need to be used with the Pro image from now on.
You should be able to easily fix your issue by setting an API key when starting LocalStack with the CLI. It will then automatically select the pro image instead. /cc @thrau

**Comment by thepalbi** [comment]
Thanks @alexrashed, ended up adding an api key and it worked! Didn't know extensions were a pro feature.
